coduno:
  url: http://localhost:6060
  runtime:
    url: http://localhost:8081
  codingcontest_url: https://codingcontest.lab.catalysts.cc
  mail:
    from: noreply@cod.uno
  invite:
    expire: P30D
  template:
    expire: PT2H
    bucket: coduno-templates
  submission:
    bucket: coduno-dev
  storage:
    gcs:
      accountId: platform-gcs@coduno.iam.gserviceaccount.com
      pkcs12: ./service-account.p12

spring:
  jpa:
    hibernate:
      ddl-auto: validate